context:
  name: faust-cchardet
  version: 2.1.19

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/faust-cchardet-${{ version }}.tar.gz
  sha256: f89386297cde0c8e0f5e21464bc2d6d0e4a4fc1b1d77cdb238ca24d740d872e0

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - pkgconfig
    - pip
  run:
    - python
  run_constraints:
    - cchardet <0

tests:
  - python:
      imports:
        - cchardet
      pip_check: true

about:
  summary: cChardet is high speed universal character encoding detector.
  license: GPL-3.0-only
  license_file:
    - COPYING
    - src/ext/uchardet/COPYING
  homepage: https://github.com/faust-streaming/cChardet

extra:
  recipe-maintainers:
    - hadim
